# -*- coding: utf-8 -*-
"""DL_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4VQ2PIDmT_HeApF8fXSTh0c17X-aUv8
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import warnings, os, math, urllib.request, io

warnings.filterwarnings('ignore')
torch.manual_seed(42)
np.random.seed(42)

os.makedirs('plots', exist_ok=True)



roll_number = "102317112"
digits      = [int(d) for d in roll_number]


digit_sum   = sum(digits)
window_size = digit_sum % 10 + 8


last_two          = int(roll_number[-2:])
prediction_horizon = last_two % 3 + 1


first_three = int(roll_number[:3])
hidden_size = first_three % 16 + 8


last_digit = digits[-1]

print("=" * 62)
print("  PERSONALIZED PARAMETERS FROM ROLL NUMBER: 102317112")
print("=" * 62)
print(f"  Digits            : {digits}")
print(f"  Sum of digits     : {digit_sum}  (1+0+2+3+1+7+1+1+2)")
print()
print(f"  window_size       = {digit_sum} % 10 + 8   =  {window_size}")
print(f"  prediction_horizon= {last_two} % 3  + 1   =  {prediction_horizon}")
print(f"  hidden_size       = {first_three} % 16 + 8  =  {hidden_size}")
print()
print(f"  Last digit: {last_digit} (EVEN)  →  Using CUSTOM RNN")
print("=" * 62)




def load_electricity_data():

    url = ("https://raw.githubusercontent.com/jbrownlee/Datasets/"
           "master/electric_production.csv")
    try:
        print("  Downloading electricity dataset...")
        resp = urllib.request.urlopen(url, timeout=10)
        df   = pd.read_csv(io.BytesIO(resp.read()), header=0,
                           index_col=0, parse_dates=True)
        df.columns = ['electricity']
        print(f"  ✓ Electricity dataset: {len(df)} monthly records (US electric production)")
        return df['electricity'].values.astype(np.float32), "Monthly US Electric Production"
    except Exception as e:
        print(f"  ⚠ Download failed ({e}) — generating synthetic electricity data")
        t = np.arange(400)
        data = (
            200 + 0.15 * t                            # upward trend
            + 40  * np.sin(2 * np.pi * t / 12)       # annual seasonality
            + 15  * np.sin(2 * np.pi * t / 3)        # quarterly fluctuation
            + 8   * np.random.randn(400)              # random noise
        ).clip(min=50)
        return data.astype(np.float32), "Synthetic Electricity (fallback)"


def load_realworld_data():

    url = ("https://raw.githubusercontent.com/jbrownlee/Datasets/"
           "master/airline-passengers.csv")
    try:
        print("  Downloading airline-passengers dataset...")
        resp = urllib.request.urlopen(url, timeout=10)
        df   = pd.read_csv(io.BytesIO(resp.read()), header=0, usecols=[1])
        values = df.values.flatten().astype(np.float32)
        print(f"  ✓ Real-world dataset: {len(values)} monthly records (Airline Passengers)")
        return values, "Monthly Airline Passengers (Box-Jenkins)"
    except Exception as e:
        print(f"  ⚠ Download failed ({e}) — generating CO2-like trend data")
        t    = np.arange(300)
        data = (315 + 0.12 * t
                + 5  * np.sin(2 * np.pi * t / 12)
                + np.random.randn(300) * 1.5)
        return data.astype(np.float32), "Synthetic CO2-like trend (fallback)"




def create_windows(data, window_size, prediction_horizon):

    X_list, y_list = [], []
    total_len = len(data)
    for i in range(total_len - window_size - prediction_horizon + 1):
        X_list.append(data[i : i + window_size])
        y_list.append(data[i + window_size : i + window_size + prediction_horizon])
    return np.array(X_list, dtype=np.float32), np.array(y_list, dtype=np.float32)


def preprocess_data(data, window_size, prediction_horizon, train_ratio=0.8):

    # Step 1: Normalize
    scaler     = MinMaxScaler(feature_range=(0, 1))
    data_norm  = scaler.fit_transform(data.reshape(-1, 1)).flatten()

    # Step 2: Create windows
    X, y = create_windows(data_norm, window_size, prediction_horizon)

    # Step 3: Chronological split
    split   = int(len(X) * train_ratio)
    X_train, X_test = X[:split], X[split:]
    y_train, y_test = y[:split], y[split:]

    # Step 4: Convert to tensors
    # RNN/Transformer expects shape (batch, seq_len, input_features)
    X_train_t = torch.FloatTensor(X_train).unsqueeze(-1)   # (N, window, 1)
    X_test_t  = torch.FloatTensor(X_test).unsqueeze(-1)    # (M, window, 1)
    y_train_t = torch.FloatTensor(y_train)                  # (N, horizon)
    y_test_t  = torch.FloatTensor(y_test)                   # (M, horizon)

    print(f"  Train samples : {len(X_train):4d}  |  X shape: {tuple(X_train_t.shape)}")
    print(f"  Test  samples : {len(X_test):4d}  |  y shape: {tuple(y_train_t.shape)}")
    return X_train_t, X_test_t, y_train_t, y_test_t, scaler



class MLP(nn.Module):

    def __init__(self, window_size, hidden_size, prediction_horizon):
        super(MLP, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(window_size, 64),
            nn.ReLU(),
            nn.Dropout(0.2),        # prevent overfitting on small datasets
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, prediction_horizon)
        )

    def forward(self, x):
        # x: (batch, window_size, 1)
        # Flatten sequence → 1D vector. MLP ignores temporal order.
        x = x.squeeze(-1)           # (batch, window_size)
        return self.net(x)          # (batch, prediction_horizon)


class CustomRNNCell(nn.Module):

    def __init__(self, input_size, hidden_size):
        super(CustomRNNCell, self).__init__()
        # Maps current input → hidden space  (includes bias b)
        self.W_ih = nn.Linear(input_size, hidden_size, bias=True)
        # Maps previous hidden state → hidden space  (no extra bias to avoid redundancy)
        self.W_hh = nn.Linear(hidden_size, hidden_size, bias=False)

    def forward(self, x_t, h_prev):

        return torch.tanh(self.W_ih(x_t) + self.W_hh(h_prev))


class CustomRNN(nn.Module):

    def __init__(self, input_size, hidden_size, prediction_horizon):
        super(CustomRNN, self).__init__()
        self.hidden_size = hidden_size
        self.cell        = CustomRNNCell(input_size, hidden_size)
        self.fc          = nn.Linear(hidden_size, prediction_horizon)

    def forward(self, x):

        batch_size = x.size(0)
        seq_len    = x.size(1)

        # h_0: zero initialization — model starts with blank memory
        h = torch.zeros(batch_size, self.hidden_size, device=x.device)

        # Unroll across time dimension
        for t in range(seq_len):
            x_t = x[:, t, :]       # (batch, input_size) — one step at a time
            h   = self.cell(x_t, h)  # update hidden state (memory)

        # h now summarizes the entire input sequence
        # Project to prediction_horizon outputs
        return self.fc(h)          # (batch, prediction_horizon)


class LSTMModel(nn.Module):

    def __init__(self, input_size, hidden_size, prediction_horizon):
        super(LSTMModel, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size,
                            num_layers=1, batch_first=True)
        self.fc   = nn.Linear(hidden_size, prediction_horizon)

    def forward(self, x):
        # out: (batch, seq, hidden) — output at each step
        # h_n: (layers, batch, hidden) — final hidden state
        out, (h_n, c_n) = self.lstm(x)
        return self.fc(out[:, -1, :])   # use last step's output


class PositionalEncoding(nn.Module):

    def __init__(self, d_model, max_len=500):
        super(PositionalEncoding, self).__init__()
        pe       = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(
            torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        # Handle odd d_model safely
        pe[:, 1::2] = torch.cos(position * div_term[:pe[:, 1::2].shape[1]])
        self.register_buffer('pe', pe.unsqueeze(0))  # (1, max_len, d_model)

    def forward(self, x):
        return x + self.pe[:, :x.size(1), :]


class TransformerModel(nn.Module):

    def __init__(self, input_size, hidden_size, prediction_horizon,
                 nhead=2, num_layers=1):
        super(TransformerModel, self).__init__()
        # Project scalar input → hidden_size (required for multi-head attention)
        self.input_proj  = nn.Linear(input_size, hidden_size)
        self.pos_enc     = PositionalEncoding(hidden_size)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_size, nhead=nhead,
            dim_feedforward=hidden_size * 4,
            dropout=0.1, batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.fc          = nn.Linear(hidden_size, prediction_horizon)

    def forward(self, x):
        x = self.input_proj(x)       # (batch, seq, hidden_size)
        x = self.pos_enc(x)          # add positional signals
        x = self.transformer(x)      # self-attention across all time steps
        return self.fc(x[:, -1, :]) # predict from last position




def train_model(model, X_train, y_train, epochs=150, lr=0.001, batch_size=32):

    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()
    dataset   = TensorDataset(X_train, y_train)
    loader    = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    losses = []
    model.train()

    for epoch in range(epochs):
        epoch_loss = 0.0
        for X_batch, y_batch in loader:
            optimizer.zero_grad()
            pred = model(X_batch)
            loss = criterion(pred, y_batch)
            loss.backward()
            # Clip gradients — critical for vanilla RNN stability
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            epoch_loss += loss.item()
        avg = epoch_loss / len(loader)
        losses.append(avg)
        if (epoch + 1) % 30 == 0:
            print(f"    Epoch {epoch+1:3d}/{epochs}  loss={avg:.6f}")

    return losses


def evaluate_model(model, X_test, y_test, scaler):

    model.eval()
    with torch.no_grad():
        pred   = model(X_test).numpy()    # (N, horizon)
        actual = y_test.numpy()           # (N, horizon)

    # Flatten horizon dimension for inverse transform
    pred_flat   = pred.reshape(-1, 1)
    actual_flat = actual.reshape(-1, 1)

    pred_orig   = scaler.inverse_transform(pred_flat).flatten()
    actual_orig = scaler.inverse_transform(actual_flat).flatten()

    mse  = mean_squared_error(actual_orig, pred_orig)
    mae  = mean_absolute_error(actual_orig, pred_orig)
    rmse = np.sqrt(mse)

    return pred_orig, actual_orig, {'MSE': mse, 'MAE': mae, 'RMSE': rmse}




def run_full_pipeline(raw_data, dataset_label, window_size,
                      prediction_horizon, hidden_size, epochs=150):
    print(f"\n{'═'*62}")
    print(f"  PIPELINE: {dataset_label}")
    print(f"  window_size={window_size}  |  horizon={prediction_horizon}  |  hidden={hidden_size}")
    print(f"{'═'*62}")

    X_train, X_test, y_train, y_test, scaler = preprocess_data(
        raw_data, window_size, prediction_horizon
    )

    # Instantiate all four models
    model_dict = {
        'MLP'        : MLP(window_size, hidden_size, prediction_horizon),
        'CustomRNN'  : CustomRNN(1, hidden_size, prediction_horizon),
        'LSTM'       : LSTMModel(1, hidden_size, prediction_horizon),
        'Transformer': TransformerModel(1, hidden_size, prediction_horizon),
    }

    all_losses  = {}
    all_results = {}

    for name, model in model_dict.items():
        print(f"\n  ▶  Training {name}...")
        losses = train_model(model, X_train, y_train, epochs=epochs)
        all_losses[name] = losses

        pred, actual, metrics = evaluate_model(model, X_test, y_test, scaler)
        all_results[name] = {'pred': pred, 'actual': actual, 'metrics': metrics}

        print(f"     MSE={metrics['MSE']:.4f}  MAE={metrics['MAE']:.4f}  RMSE={metrics['RMSE']:.4f}")

    # ── Plot 1: Training Loss ─────────────────────────────────
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    axes = axes.flatten()
    colors_loss = ['#4C72B0', '#DD8452', '#55A868', '#C44E52']
    for i, (name, losses) in enumerate(all_losses.items()):
        axes[i].plot(losses, color=colors_loss[i], linewidth=1.5)
        axes[i].set_title(f'{name}', fontsize=12, fontweight='bold')
        axes[i].set_xlabel('Epoch')
        axes[i].set_ylabel('MSE Loss')
        axes[i].grid(True, alpha=0.3)
    plt.suptitle(f'Training Loss Curves — {dataset_label}', fontsize=14, fontweight='bold')
    plt.tight_layout()
    save_path = f"plots/{dataset_label.replace(' ', '_')}_loss.png"
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\n  ✓ Loss plot saved → {save_path}")

    # ── Plot 2: Predictions vs Actual ─────────────────────────
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()
    n_show  = min(200, len(all_results['MLP']['actual']))
    actual_ref = all_results['MLP']['actual']  # same for all models

    for i, (name, res) in enumerate(all_results.items()):
        ax = axes[i]
        ax.plot(actual_ref[:n_show], color='black', linewidth=1.5,
                label='Actual', alpha=0.85)
        ax.plot(res['pred'][:n_show], color=colors_loss[i],
                linewidth=1.2, linestyle='--', label=f'{name} Pred')
        m = res['metrics']
        ax.set_title(f"{name}\nRMSE={m['RMSE']:.4f}  MAE={m['MAE']:.4f}",
                     fontsize=10)
        ax.set_xlabel('Test Time Step')
        ax.set_ylabel('Value (original scale)')
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    plt.suptitle(f'Prediction vs Actual — {dataset_label}', fontsize=14, fontweight='bold')
    plt.tight_layout()
    save_path = f"plots/{dataset_label.replace(' ', '_')}_predictions.png"
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  ✓ Prediction plot saved → {save_path}")

    return all_results, all_losses




def ablation_study(raw_data, base_window, prediction_horizon,
                   hidden_size, dataset_label, epochs=120):

    print(f"\n{'═'*62}")
    print(f"  ABLATION STUDY — CustomRNN on {dataset_label}")
    print(f"  Testing window sizes: {base_window//2}, {base_window}, {base_window*2}")
    print(f"{'═'*62}")

    configs = {
        f'Half  (ws={base_window//2})' : base_window // 2,
        f'Original (ws={base_window})': base_window,
        f'Double (ws={base_window*2})' : base_window * 2,
    }
    ablation_res = {}
    colors       = ['coral', 'steelblue', 'mediumseagreen']

    for (config_name, ws) in configs.items():
        print(f"\n  Config: {config_name}")
        X_train, X_test, y_train, y_test, scaler = preprocess_data(
            raw_data, ws, prediction_horizon
        )
        model  = CustomRNN(1, hidden_size, prediction_horizon)
        losses = train_model(model, X_train, y_train, epochs=epochs)
        pred, actual, metrics = evaluate_model(model, X_test, y_test, scaler)
        ablation_res[config_name] = {
            'ws': ws, 'pred': pred, 'actual': actual,
            'metrics': metrics, 'losses': losses
        }
        print(f"    RMSE={metrics['RMSE']:.4f}  MAE={metrics['MAE']:.4f}")

    # ── Plot: Prediction comparison across window sizes ───────
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    for i, ((name, res), c) in enumerate(zip(ablation_res.items(), colors)):
        ax     = axes[i]
        n_show = min(150, len(res['pred']))
        ax.plot(res['actual'][:n_show], 'k-', linewidth=1.5, label='Actual')
        ax.plot(res['pred'][:n_show],   '--', color=c, linewidth=1.2, label='Predicted')
        ax.set_title(f"{name}\nRMSE={res['metrics']['RMSE']:.4f}", fontsize=10)
        ax.set_xlabel('Test Time Step')
        ax.set_ylabel('Value')
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    plt.suptitle(f'Ablation Study: Window Size Effect — {dataset_label}',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    save_path = f"plots/{dataset_label.replace(' ', '_')}_ablation.png"
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()

    # ── Plot: RMSE bar chart ───────────────────────────────────
    fig, ax = plt.subplots(figsize=(8, 5))
    names = list(ablation_res.keys())
    rmses = [ablation_res[n]['metrics']['RMSE'] for n in names]
    bars  = ax.bar(names, rmses, color=colors, edgecolor='black', width=0.5)
    for bar, val in zip(bars, rmses):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + max(rmses) * 0.01,
                f'{val:.4f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
    ax.set_title(f'RMSE vs Window Size — {dataset_label}', fontsize=13)
    ax.set_ylabel('RMSE (original scale)')
    ax.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    save2 = f"plots/{dataset_label.replace(' ', '_')}_ablation_bar.png"
    plt.savefig(save2, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\n  ✓ Ablation plots saved → {save_path}, {save2}")

    return ablation_res




def failure_analysis(results, dataset_label):

    pred   = results['CustomRNN']['pred']
    actual = results['CustomRNN']['actual']
    errors = np.abs(pred - actual)

    # Threshold: top 10% = "failure region"
    threshold   = np.percentile(errors, 90)
    failure_idx = np.where(errors > threshold)[0]

    fig, axes = plt.subplots(3, 1, figsize=(14, 13))

    # ── Sub-plot 1: Prediction with failure regions marked ─────
    ax1    = axes[0]
    n_show = min(300, len(pred))
    ax1.plot(actual[:n_show], 'k-', linewidth=1.5, label='Actual', alpha=0.9)
    ax1.plot(pred[:n_show],   'r--', linewidth=1.2, label='CustomRNN Prediction', alpha=0.8)
    fail_in_view = failure_idx[failure_idx < n_show]
    ax1.scatter(fail_in_view, actual[fail_in_view],
                color='red', s=25, zorder=5,
                label=f'Top 10% Error Regions ({len(fail_in_view)} pts)')
    ax1.set_title('CustomRNN — Prediction vs Actual  (red dots = worst errors)',
                  fontsize=11)
    ax1.legend(fontsize=9)
    ax1.grid(True, alpha=0.3)
    ax1.set_ylabel('Value (original scale)')

    # ── Sub-plot 2: Absolute error over time ───────────────────
    ax2 = axes[1]
    ax2.fill_between(range(n_show), errors[:n_show],
                     color='darkorange', alpha=0.4)
    ax2.plot(errors[:n_show], color='darkorange', linewidth=1.0)
    ax2.axhline(y=threshold, color='red', linestyle='--', linewidth=1.5,
                label=f'90th pct threshold = {threshold:.3f}')
    ax2.set_title('Absolute Error  |predicted − actual|  over Time', fontsize=11)
    ax2.set_ylabel('Absolute Error')
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.3)

    # ── Sub-plot 3: Error histogram ────────────────────────────
    ax3 = axes[2]
    ax3.hist(errors, bins=40, color='steelblue', edgecolor='white', alpha=0.85)
    ax3.axvline(x=np.mean(errors), color='red',    linestyle='--',
                label=f'Mean error   = {np.mean(errors):.4f}')
    ax3.axvline(x=threshold,       color='orange', linestyle='--',
                label=f'90th pct     = {threshold:.4f}')
    ax3.set_title('Error Distribution', fontsize=11)
    ax3.set_xlabel('Absolute Error')
    ax3.set_ylabel('Frequency')
    ax3.legend(fontsize=9)
    ax3.grid(True, alpha=0.3)

    plt.suptitle(f'Failure Analysis — CustomRNN on {dataset_label}',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    save_path = f"plots/{dataset_label.replace(' ', '_')}_failure.png"
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()

    # Print summary
    bias = np.mean(pred - actual)
    print(f"\n  FAILURE ANALYSIS — {dataset_label}")
    print(f"  {'─'*45}")
    print(f"  Total test samples      : {len(errors)}")
    print(f"  High-error samples (>90th pct) : {len(failure_idx)}  ({100*len(failure_idx)/len(errors):.1f}%)")
    print(f"  Mean absolute error     : {np.mean(errors):.4f}")
    print(f"  Median absolute error   : {np.median(errors):.4f}")
    print(f"  Max absolute error      : {np.max(errors):.4f}")
    print(f"  Error std deviation     : {np.std(errors):.4f}")
    print(f"  Systematic bias         : {bias:+.4f}  ", end="")
    print("(tends to OVER-predict)" if bias > 0 else "(tends to UNDER-predict)")
    print(f"  ✓ Failure plot saved → {save_path}")

    return errors, failure_idx




def plot_model_comparison(elec_results, real_results, elec_label, real_label):
    model_names  = list(elec_results.keys())
    colors_bar   = ['#4C72B0', '#DD8452', '#55A868', '#C44E52']

    fig, axes = plt.subplots(1, 3, figsize=(17, 5))

    for ax, (ds_label, results) in zip(axes[:2],
            [(elec_label, elec_results), (real_label, real_results)]):
        rmses = [results[m]['metrics']['RMSE'] for m in model_names]
        bars  = ax.bar(model_names, rmses, color=colors_bar, edgecolor='black')
        for bar, val in zip(bars, rmses):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + max(rmses) * 0.01,
                    f'{val:.3f}', ha='center', va='bottom', fontsize=9)
        ax.set_title(f'RMSE — {ds_label}', fontsize=11)
        ax.set_ylabel('RMSE')
        ax.grid(True, alpha=0.3, axis='y')
        ax.tick_params(axis='x', rotation=15)

    # Table: metrics side-by-side
    ax3 = axes[2]
    ax3.axis('off')
    metrics_data = []
    for name in model_names:
        em = elec_results[name]['metrics']
        rm = real_results[name]['metrics']
        metrics_data.append([
            name,
            f"{em['RMSE']:.4f}", f"{em['MAE']:.4f}",
            f"{rm['RMSE']:.4f}", f"{rm['MAE']:.4f}",
        ])
    col_labels = ['Model', 'E-RMSE', 'E-MAE', 'R-RMSE', 'R-MAE']
    tbl = ax3.table(cellText=metrics_data, colLabels=col_labels,
                    loc='center', cellLoc='center')
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9)
    tbl.scale(1.2, 1.8)
    ax3.set_title('Metrics Summary  (E=Electricity, R=Real-world)', fontsize=10)

    plt.suptitle('Overall Model Comparison', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig('plots/model_comparison.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("\n  ✓ Model comparison plot saved → plots/model_comparison.png")




if __name__ == "__main__":

    print("\n" + "█" * 62)
    print("  LOADING DATASETS")
    print("█" * 62)
    elec_data,  elec_label  = load_electricity_data()
    real_data,  real_label  = load_realworld_data()

    # ── Pipeline: Electricity ─────────────────────────────────
    elec_results, elec_losses = run_full_pipeline(
        elec_data, elec_label,
        window_size, prediction_horizon, hidden_size,
        epochs=150
    )

    # ── Pipeline: Real-world ──────────────────────────────────
    real_results, real_losses = run_full_pipeline(
        real_data, real_label,
        window_size, prediction_horizon, hidden_size,
        epochs=150
    )

    # ── Ablation Study (on electricity) ───────────────────────
    ablation_results = ablation_study(
        elec_data, window_size, prediction_horizon, hidden_size,
        dataset_label=elec_label, epochs=120
    )

    # ── Failure Analysis ──────────────────────────────────────
    print(f"\n{'█'*62}")
    print("  FAILURE ANALYSIS")
    print(f"{'█'*62}")
    failure_analysis(elec_results,  elec_label)
    failure_analysis(real_results,  real_label)

    # ── Summary Comparison ────────────────────────────────────
    plot_model_comparison(elec_results, real_results, elec_label, real_label)

    # ── Final Metrics Table ───────────────────────────────────
    print(f"\n{'═'*62}")
    print("  FINAL METRICS TABLE")
    print(f"{'═'*62}")
    for ds_label, results in [(elec_label, elec_results), (real_label, real_results)]:
        print(f"\n  {ds_label}")
        print(f"  {'Model':<15} {'MSE':>10} {'MAE':>10} {'RMSE':>10}")
        print(f"  {'─'*48}")
        for name, res in results.items():
            m = res['metrics']
            print(f"  {name:<15} {m['MSE']:>10.4f} {m['MAE']:>10.4f} {m['RMSE']:>10.4f}")

    print(f"\n{'═'*62}")
    print("  ALL DONE! All plots saved to ./plots/ directory")
    print(f"  window_size={window_size} | horizon={prediction_horizon} | hidden={hidden_size}")
    print(f"  Model: Custom RNN (roll digit={last_digit}, EVEN)")
    print(f"{'═'*62}\n")

